import { db, schemesTable, sectorsTable } from "@workspace/db";

const sectors = [
  { sectorId: "education", name: "Education", nameHindi: "शिक्षा", ageGroups: ["teen", "youngAdult"], icon: "GraduationCap" },
  { sectorId: "scholarship", name: "Scholarship", nameHindi: "छात्रवृत्ति", ageGroups: ["teen", "youngAdult"], icon: "BookOpen" },
  { sectorId: "skill-training", name: "Skill Training", nameHindi: "कौशल प्रशिक्षण", ageGroups: ["teen", "youngAdult"], icon: "Wrench" },
  { sectorId: "sports", name: "Sports", nameHindi: "खेल", ageGroups: ["teen"], icon: "Trophy" },
  { sectorId: "digital-literacy", name: "Digital Literacy", nameHindi: "डिजिटल साक्षरता", ageGroups: ["teen"], icon: "Monitor" },
  { sectorId: "startup-business", name: "Startup & Business", nameHindi: "स्टार्टअप और व्यवसाय", ageGroups: ["youngAdult", "middleAge"], icon: "Briefcase" },
  { sectorId: "housing", name: "Housing", nameHindi: "आवास", ageGroups: ["youngAdult", "middleAge"], icon: "Home" },
  { sectorId: "employment", name: "Employment", nameHindi: "रोजगार", ageGroups: ["youngAdult", "middleAge"], icon: "Building2" },
  { sectorId: "higher-education", name: "Higher Education", nameHindi: "उच्च शिक्षा", ageGroups: ["youngAdult"], icon: "University" },
  { sectorId: "health-insurance", name: "Health Insurance", nameHindi: "स्वास्थ्य बीमा", ageGroups: ["youngAdult", "middleAge", "senior"], icon: "Heart" },
  { sectorId: "business-loans", name: "Business Loans", nameHindi: "व्यापार ऋण", ageGroups: ["middleAge", "youngAdult"], icon: "Banknote" },
  { sectorId: "tax-benefits", name: "Tax Benefits", nameHindi: "कर लाभ", ageGroups: ["middleAge"], icon: "Calculator" },
  { sectorId: "agriculture", name: "Agriculture", nameHindi: "कृषि", ageGroups: ["middleAge", "senior"], icon: "Wheat" },
  { sectorId: "pension", name: "Pension", nameHindi: "पेंशन", ageGroups: ["senior"], icon: "PiggyBank" },
  { sectorId: "old-age-support", name: "Old Age Support", nameHindi: "वृद्धावस्था सहायता", ageGroups: ["senior"], icon: "Users" },
  { sectorId: "social-security", name: "Social Security", nameHindi: "सामाजिक सुरक्षा", ageGroups: ["senior", "middleAge"], icon: "Shield" },
];

const schemes = [
  // ──────────────── TEEN SCHEMES ────────────────
  {
    id: "pm-scholarship-001",
    name: "PM Scholarship Scheme",
    nameHindi: "पीएम छात्रवृत्ति योजना",
    ministry: "Ministry of Education",
    ageGroups: ["teen", "youngAdult"],
    sectors: ["education", "scholarship"],
    incomeLimit: 800000,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹25,000/year scholarship",
    description: "The Prime Minister's Scholarship Scheme (PMSS) provides financial assistance to the wards and widows of Ex-Servicemen and Ex-Coast Guard personnel for pursuing professional degree courses. The scheme covers MBBS, BDS, BE, BTech, BEd, BBA, BCA, BPharma, Nursing, and other recognized professional courses.\n\nMale scholars receive ₹2,500 per month and female scholars receive ₹3,000 per month, providing crucial financial support during their academic journey.",
    eligibility: ["Indian citizen", "Age 13-25", "Min 60% marks in last exam", "Ward/widow of Ex-Serviceman or Ex-Coast Guard", "Pursuing professional degree course", "Annual family income below ₹8 lakhs"],
    documents: ["Aadhaar Card", "Income Certificate", "Marksheet (last qualifying exam)", "Bank Passbook", "Ex-Serviceman certificate", "Discharge certificate of parent"],
    howToApply: "1. Visit the National Scholarship Portal at scholarships.gov.in\n2. Register with your mobile number and Aadhaar\n3. Fill the application form with your personal and academic details\n4. Upload all required documents\n5. Submit the application before the deadline\n6. Track application status on the portal",
    officialLink: "https://scholarships.gov.in",
    deadline: "31 December 2025",
    termsAndConditions: ["Scholarship is renewable annually subject to satisfactory academic performance", "Minimum 60% marks required to continue receiving scholarship", "Scholar must not be receiving any other government scholarship", "Must inform the authority if leaving the course"],
    isState: false,
    state: null,
    tags: ["education", "money", "scholarship", "ex-serviceman"],
    popularityScore: 95,
  },
  {
    id: "nmmss-002",
    name: "National Means-cum-Merit Scholarship",
    nameHindi: "राष्ट्रीय साधन-सह-मेरिट छात्रवृत्ति",
    ministry: "Ministry of Education",
    ageGroups: ["teen"],
    sectors: ["education", "scholarship"],
    incomeLimit: 150000,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹12,000/year scholarship for Class 9-12",
    description: "The National Means-cum-Merit Scholarship Scheme (NMMSS) awards scholarships to meritorious students of economically weaker sections to arrest their dropout at class VIII and encourage them to continue education at secondary stage.\n\nOne lakh fresh scholarships are awarded every year to selected students of class IX at ₹12,000 per annum (₹1,000 per month) for Classes IX to XII in government and aided schools.",
    eligibility: ["Indian citizen", "Studying in Class 9-12", "Min 55% in Class 7 (50% for SC/ST)", "Annual family income below ₹1.5 lakh", "Studying in Government or aided school"],
    documents: ["Aadhaar Card", "Income Certificate", "Class 7 Marksheet", "Bank Passbook", "Caste Certificate (if applicable)", "School Certificate"],
    howToApply: "1. Students are identified through a State Level Examination\n2. Apply through your school or state education department\n3. Visit the National Scholarship Portal for online application\n4. Submit required documents to school principal\n5. School forwards applications to district education officer",
    officialLink: "https://scholarships.gov.in",
    deadline: "30 November 2025",
    termsAndConditions: ["Renewable annually with 55% marks (50% for SC/ST)", "Valid for studies in government schools only", "Scholar cannot receive other government scholarship simultaneously", "Must maintain regular attendance"],
    isState: false,
    state: null,
    tags: ["education", "merit", "scholarship", "school"],
    popularityScore: 88,
  },
  {
    id: "bbbp-003",
    name: "Beti Bachao Beti Padhao",
    nameHindi: "बेटी बचाओ बेटी पढ़ाओ",
    ministry: "Ministry of Women and Child Development",
    ageGroups: ["teen"],
    sectors: ["education", "skill-training"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Financial support, education grants, and awareness programs for girl children",
    description: "Beti Bachao Beti Padhao (BBBP) is a flagship scheme to address the declining Child Sex Ratio and promote women's empowerment. The scheme provides comprehensive support through convergent action of three ministries.\n\nBenefits include scholarship support for girl students, awareness campaigns, and the Sukanya Samriddhi Account for tax-free savings that matures when the girl turns 21.",
    eligibility: ["Girl child, any age", "Indian citizen", "All income groups eligible", "Priority to districts with low sex ratio"],
    documents: ["Birth certificate", "Aadhaar Card", "Bank account (Sukanya Samriddhi)", "School enrollment certificate"],
    howToApply: "1. Visit the nearest Anganwadi centre or CSC\n2. Open a Sukanya Samriddhi Account at any Post Office or authorized bank\n3. Deposit minimum ₹250 annually\n4. Account matures when girl turns 21 or on marriage after age 18\n5. Access scholarships through district education office",
    officialLink: "https://wcd.nic.in/bbbp-schemes",
    deadline: null,
    termsAndConditions: ["Sukanya Samriddhi Account must be opened before age 10", "Account can be continued till 21 years", "Partial withdrawal of 50% allowed after age 18 for education", "Premature closure only on death or life-threatening disease"],
    isState: false,
    state: null,
    tags: ["girl child", "education", "women", "social"],
    popularityScore: 92,
  },
  {
    id: "pmkvy-004",
    name: "Pradhan Mantri Kaushal Vikas Yojana",
    nameHindi: "प्रधानमंत्री कौशल विकास योजना",
    ministry: "Ministry of Skill Development and Entrepreneurship",
    ageGroups: ["teen", "youngAdult"],
    sectors: ["skill-training", "employment"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Free skill certification + ₹8,000 reward on certification",
    description: "Pradhan Mantri Kaushal Vikas Yojana (PMKVY) enables Indian youth to take up industry-relevant skill training. Training and Assessment fees are completely paid by the Government. PMKVY covers 300+ job roles and provides monetary rewards for successful training and certification.",
    eligibility: ["Indian citizen", "Age 15-45 years", "Unemployed or looking for skill upgrade", "Class 8 dropouts eligible for some courses", "Aadhaar card mandatory"],
    documents: ["Aadhaar Card", "Bank Passbook", "Passport size photograph", "Educational certificates", "Mobile number"],
    howToApply: "1. Visit the official portal at pmkvyofficial.org\n2. Find a PMKVY Training Centre near you\n3. Choose from 300+ job roles\n4. Register at the training centre with required documents\n5. Complete the training course\n6. Appear for the certification exam\n7. Receive certificate and monetary reward",
    officialLink: "https://pmkvyofficial.org",
    deadline: null,
    termsAndConditions: ["Training is completely free for candidates", "Monetary reward paid only after certification", "Must complete the full course and pass assessment", "Cannot enroll in same job role twice"],
    isState: false,
    state: null,
    tags: ["skill", "training", "employment", "youth"],
    popularityScore: 90,
  },
  {
    id: "inspire-018",
    name: "INSPIRE Scholarship for Higher Education",
    nameHindi: "इंस्पायर उच्च शिक्षा छात्रवृत्ति",
    ministry: "Department of Science & Technology",
    ageGroups: ["teen", "youngAdult"],
    sectors: ["education", "scholarship"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹80,000/year scholarship for 5 years (BSc/BS/Int. MSc courses)",
    description: "Innovation in Science Pursuit for Inspired Research (INSPIRE) is a national programme implemented by the Department of Science & Technology. The Scholarship for Higher Education (SHE) component aims to attract talented youth to study science at the undergraduate and postgraduate level.\n\nTop 1% students in Class XII Board exams and toppers in various merit lists are eligible. The scholarship is ₹80,000 per year for 5 years, covering the complete duration of BSc/BS/Integrated MSc/MS programmes.",
    eligibility: ["Indian citizen", "Top 1% in Class XII Board exam or equivalent merit list", "Pursuing BSc/BS/Integrated MSc in Natural/Basic Sciences", "Admitted in recognized Indian institution", "Age up to 22 years at time of joining"],
    documents: ["Aadhaar Card", "Class XII Marksheet & Certificate", "Admission proof from recognized institution", "Bank Passbook", "Passport photograph"],
    howToApply: "1. Check eligibility on online-inspire.gov.in\n2. Submit online application with required documents\n3. Verification done by DST\n4. Scholarship credited annually to bank account\n5. Mentorship from senior scientists provided",
    officialLink: "https://online-inspire.gov.in",
    deadline: "30 September each year",
    termsAndConditions: ["Must pursue science courses only", "Renewal subject to satisfactory academic performance", "Cannot combine with other DST scholarships", "Must maintain 60% marks each year"],
    isState: false,
    state: null,
    tags: ["science", "scholarship", "higher education", "research"],
    popularityScore: 77,
  },
  {
    id: "khelo-india-019",
    name: "Khelo India Youth Games",
    nameHindi: "खेलो इंडिया यूथ गेम्स",
    ministry: "Ministry of Youth Affairs and Sports",
    ageGroups: ["teen"],
    sectors: ["sports"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹5 lakh/year scholarship for 8 years for identified athletes",
    description: "Khelo India is the flagship programme of the Ministry of Youth Affairs and Sports to revive the sports culture in India at the grassroots level. The programme provides financial support of ₹5 lakh per year for 8 years to athletes identified as talented during the Khelo India Games.\n\nThe scheme covers 20+ sports disciplines, provides world-class training facilities, sports science support, and helps athletes build a career in sports while continuing their education.",
    eligibility: ["Indian citizen", "Age 8-18 years", "Identified as talented athlete at Khelo India Games", "Pursuing formal education", "Recommended by State Sports Authority"],
    documents: ["Birth Certificate", "Aadhaar Card", "Sports achievement certificates", "School enrollment certificate", "Photograph", "Bank account details"],
    howToApply: "1. Participate in Khelo India Youth Games (held annually)\n2. Outperform and get selected by expert committee\n3. Get recommendation from State Sports Association\n4. Apply at the Khelo India portal kheloindia.gov.in\n5. Annual scholarship disbursed directly to bank account",
    officialLink: "https://kheloindia.gov.in",
    deadline: null,
    termsAndConditions: ["Must continue formal education alongside sports training", "Annual performance review for scholarship renewal", "Must represent India in national/international competitions when selected", "Cannot receive other government sports scholarship simultaneously"],
    isState: false,
    state: null,
    tags: ["sports", "athlete", "youth", "scholarship"],
    popularityScore: 73,
  },
  {
    id: "pm-poshan-020",
    name: "PM POSHAN Scheme (Mid-Day Meal)",
    nameHindi: "पीएम पोषण शक्ति निर्माण योजना",
    ministry: "Ministry of Education",
    ageGroups: ["teen"],
    sectors: ["education"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Free nutritious mid-day meal at school every day",
    description: "PM POSHAN Shakti Nirman (formerly Mid-Day Meal Scheme) is the world's largest school feeding programme, providing hot cooked meals to students of Classes 1 to 8 in government and aided schools. The scheme covers about 12 crore children across 11.5 lakh schools.\n\nNutritious meals reduce hunger and improve attendance, enrolment, and retention. The scheme also provides additional nutrition for children from disadvantaged backgrounds, with menus prescribed by nutritionists.",
    eligibility: ["Students of Class 1-8", "Studying in government or government-aided school", "Automatically eligible – no application needed", "All categories"],
    documents: ["School enrollment (automatic benefit)", "No separate documents required"],
    howToApply: "1. Enroll your child in any government or aided school\n2. The school automatically provides the mid-day meal every school day\n3. No separate application required\n4. Parents can check menu and quality through School Management Committee",
    officialLink: "https://pmposhan.education.gov.in",
    deadline: null,
    termsAndConditions: ["Available only on school days", "Meal must meet prescribed nutritional norms", "Cooking must be done in clean hygienic environment", "States can supplement with additional items"],
    isState: false,
    state: null,
    tags: ["nutrition", "school", "meal", "children"],
    popularityScore: 85,
  },
  {
    id: "pre-matric-sc-021",
    name: "Pre-Matric Scholarship for SC Students",
    nameHindi: "एससी छात्रों के लिए प्री-मैट्रिक छात्रवृत्ति",
    ministry: "Ministry of Social Justice and Empowerment",
    ageGroups: ["teen"],
    sectors: ["education", "scholarship"],
    incomeLimit: 250000,
    categories: ["sc"],
    benefit: "₹150-₹350/month + book grant ₹750-₹1000/year",
    description: "Pre-Matric Scholarship for SC students supports Scheduled Caste students studying in Classes 9 and 10 to prevent dropout and encourage continuation of education. The scholarship covers maintenance allowance, reader allowance for blind students, and additional allowances for disabled students.\n\nDay scholars receive ₹150/month (Class 9) or ₹160/month (Class 10), while hostellers receive ₹350/month, plus a book grant of ₹750 per annum.",
    eligibility: ["Scheduled Caste student", "Studying in Class 9 or 10", "Annual family income below ₹2.5 lakh", "Indian citizen", "Not receiving other scholarship"],
    documents: ["Aadhaar Card", "Caste Certificate (SC)", "Income Certificate", "Previous class Marksheet", "Bank Passbook", "School Certificate"],
    howToApply: "1. Apply through National Scholarship Portal scholarships.gov.in\n2. Or apply through State Social Welfare Department\n3. Get school principal's recommendation\n4. Submit all documents before deadline\n5. Track status on portal",
    officialLink: "https://scholarships.gov.in",
    deadline: "31 October each year",
    termsAndConditions: ["Must score minimum 55% in previous class", "Scholarship stops if student fails twice in same class", "Must not receive other central government scholarship", "Disciplinary action can lead to cancellation"],
    isState: false,
    state: null,
    tags: ["SC", "scholarship", "pre-matric", "school"],
    popularityScore: 80,
  },

  // ──────────────── YOUNG ADULT SCHEMES ────────────────
  {
    id: "pm-mudra-005",
    name: "PM Mudra Yojana",
    nameHindi: "प्रधानमंत्री मुद्रा योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["startup-business", "business-loans"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st", "women"],
    benefit: "Loans from ₹50,000 to ₹10 lakh without collateral",
    description: "Pradhan Mantri MUDRA Yojana (PMMY) provides financial support to micro/small businesses through three categories: Shishu (up to ₹50,000), Kishore (₹50,001–₹5 lakh), and Tarun (₹5,00,001–₹10 lakh).\n\nNo collateral is required, making it accessible for first-time entrepreneurs and small business owners. Women entrepreneurs, SC/ST entrepreneurs get priority.",
    eligibility: ["Indian citizen", "Age 18 and above", "Non-corporate small business owner or entrepreneur", "Viable business plan required", "Not a defaulter on previous loans"],
    documents: ["Aadhaar Card", "PAN Card", "Business plan/proof of business", "Bank statements (6 months)", "Proof of SC/ST/OBC (if applicable)", "Photographs"],
    howToApply: "1. Approach any nationalized bank, RRB, cooperative bank, MFI, or NBFC\n2. Fill the MUDRA loan application form\n3. Submit business plan and required documents\n4. Bank assesses the application\n5. Loan sanctioned and disbursed to bank account\n6. MUDRA card issued for Shishu category",
    officialLink: "https://www.mudra.org.in",
    deadline: null,
    termsAndConditions: ["Interest rates vary by bank and loan category", "Repayment period up to 5 years", "No collateral required", "Can be used for business purposes only"],
    isState: false,
    state: null,
    tags: ["loan", "business", "entrepreneur", "self-employment"],
    popularityScore: 96,
  },
  {
    id: "startup-india-006",
    name: "Startup India Seed Fund",
    nameHindi: "स्टार्टअप इंडिया सीड फंड",
    ministry: "Ministry of Commerce and Industry",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["startup-business"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st", "women"],
    benefit: "Up to ₹50 lakh seed funding for startups",
    description: "The Startup India Seed Fund Scheme (SISFS) provides financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization. Grants of up to ₹20 lakh for validation and investments of up to ₹50 lakh for market entry.\n\nStartups get this funding through empaneled incubators to build their MVP and attract larger investments.",
    eligibility: ["DPIIT recognized startup", "Incorporated less than 2 years ago", "Must not have received more than ₹10 lakh from Government", "Working on innovative product/service", "Must be selected by empaneled incubator"],
    documents: ["DPIIT recognition certificate", "Incorporation certificate", "Detailed business plan", "Pitch deck", "Bank account details", "Founders' Aadhaar and PAN"],
    howToApply: "1. Get DPIIT recognition at startupindia.gov.in\n2. Apply through an empaneled incubator\n3. Submit business plan and pitch deck\n4. Present to incubator selection committee\n5. If selected, sign agreement with incubator\n6. Receive milestone-based funding",
    officialLink: "https://seedfund.startupindia.gov.in",
    deadline: null,
    termsAndConditions: ["Grant portion is non-repayable", "Investment portion may be converted to equity or royalty", "Funds must be used for stated business purposes", "Regular progress reports required"],
    isState: false,
    state: null,
    tags: ["startup", "funding", "innovation", "entrepreneurship"],
    popularityScore: 82,
  },
  {
    id: "pm-awas-007",
    name: "PM Awas Yojana (Urban)",
    nameHindi: "प्रधानमंत्री आवास योजना (शहरी)",
    ministry: "Ministry of Housing and Urban Affairs",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["housing"],
    incomeLimit: 1800000,
    categories: ["general", "obc", "sc", "st", "women"],
    benefit: "Up to ₹2.67 lakh subsidy on home loans",
    description: "Pradhan Mantri Awas Yojana - Urban (PMAY-U) aims to provide affordable housing to the urban poor. The Credit Linked Subsidy Scheme (CLSS) offers interest subsidy of 6.5% for EWS/LIG on housing loan up to ₹6 lakh.\n\nBeneficiaries can avail benefits if they do not own a pucca house in any part of India.",
    eligibility: ["Indian citizen", "No pucca house in any part of India", "Annual income up to ₹18 lakh (MIG category)", "First-time home buyer", "Adult female member preferred as co-owner"],
    documents: ["Aadhaar Card", "PAN Card", "Income proof", "Bank statements", "Property documents", "Self-declaration of no house ownership"],
    howToApply: "1. Apply online at pmaymis.gov.in or through any empaneled bank\n2. Select the appropriate income category (EWS/LIG/MIG)\n3. Submit all required documents\n4. Bank verifies eligibility and processes the loan\n5. Subsidy is credited directly to your loan account",
    officialLink: "https://pmaymis.gov.in",
    deadline: "31 December 2024",
    termsAndConditions: ["Subsidy available only once per family", "Female ownership or co-ownership mandatory for EWS/LIG", "Interest subsidy is on Net Present Value basis", "Cannot combine with other housing subsidies"],
    isState: false,
    state: null,
    tags: ["housing", "home loan", "subsidy", "urban"],
    popularityScore: 94,
  },
  {
    id: "ayushman-bharat-008",
    name: "Ayushman Bharat - PM Jan Arogya Yojana",
    nameHindi: "आयुष्मान भारत - प्रधानमंत्री जन आरोग्य योजना",
    ministry: "Ministry of Health and Family Welfare",
    ageGroups: ["youngAdult", "middleAge", "senior"],
    sectors: ["health-insurance"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹5 lakh health coverage per family per year",
    description: "Ayushman Bharat PM-PMJAY is the world's largest government-funded health insurance scheme providing ₹5 lakh per family per year for secondary and tertiary care hospitalization to over 10.74 crore poor and vulnerable families.\n\nCovers about 1,393 medical and surgical packages. Cashless treatment at empaneled public and private hospitals. No cap on family size or age.",
    eligibility: ["Listed in SECC 2011 database", "No upper age limit", "No limit on family size", "Pre-existing conditions covered", "Portability across India"],
    documents: ["Aadhaar Card", "Ration Card", "Family income proof", "SECC enrollment verification"],
    howToApply: "1. Check eligibility at pmjay.gov.in or call 14555\n2. Visit the nearest Ayushman Mitra at empaneled hospital\n3. Verify through Aadhaar-based eKYC\n4. Get Ayushman Bharat Golden Card issued\n5. Present card at empaneled hospital for cashless treatment",
    officialLink: "https://pmjay.gov.in",
    deadline: null,
    termsAndConditions: ["Coverage is per family, not individual", "Hospitalization only (OPD not covered)", "Only at empaneled hospitals", "Pre-existing diseases covered from day 1"],
    isState: false,
    state: null,
    tags: ["health", "insurance", "hospitalization", "medical"],
    popularityScore: 98,
  },
  {
    id: "pm-ujjwala-022",
    name: "PM Ujjwala Yojana 2.0",
    nameHindi: "प्रधानमंत्री उज्ज्वला योजना 2.0",
    ministry: "Ministry of Petroleum and Natural Gas",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Free LPG connection + first refill free + stove free",
    description: "Pradhan Mantri Ujjwala Yojana 2.0 provides free LPG connections to adult women of Below Poverty Line households who do not already have a connection. The scheme aims to replace polluting cooking fuels with cleaner LPG.\n\nBeneficiaries get a free LPG connection, first refill free, and a free stove (in many cases). Migrant workers can get connections even without permanent address proof by submitting a self-declaration.",
    eligibility: ["Adult woman (age 18+)", "BPL household or SECC listed", "No existing LPG connection in household", "Indian citizen", "Active bank account required"],
    documents: ["Aadhaar Card", "Ration Card / BPL Certificate", "Bank account passbook", "Address proof (self-declaration for migrants)", "Photograph"],
    howToApply: "1. Visit the nearest LPG distributor (HP/Bharat/Indane Gas)\n2. Fill the KYC form and application form\n3. Submit documents including Aadhaar and BPL proof\n4. Connection issued immediately on verification\n5. First refill and stove provided free",
    officialLink: "https://pmuy.gov.in",
    deadline: null,
    termsAndConditions: ["Only one connection per household", "Must be in woman's name", "Subsequent refills at market price (EMI option available)", "Cannot transfer connection to another person"],
    isState: false,
    state: null,
    tags: ["LPG", "cooking gas", "women", "BPL"],
    popularityScore: 91,
  },
  {
    id: "e-shram-023",
    name: "e-SHRAM Card Registration",
    nameHindi: "ई-श्रम कार्ड पंजीकरण",
    ministry: "Ministry of Labour and Employment",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["social-security", "employment"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Free accident insurance ₹2 lakh + access to all social security schemes",
    description: "e-SHRAM is the national database of unorganised workers in India. Registering on e-SHRAM gives workers a Unique Worker Identification Number (UWIN) and access to social security benefits.\n\nRegistered workers get ₹2 lakh accident insurance under PM Suraksha Bima Yojana free for one year. The card helps workers access welfare schemes, get priority in future government benefits, and build a verified work history.",
    eligibility: ["Unorganised sector worker", "Age 16-59 years", "Not a member of EPFO or ESIC", "Indian citizen", "Active mobile number linked to Aadhaar"],
    documents: ["Aadhaar Card", "Bank account linked to Aadhaar", "Mobile number linked to Aadhaar"],
    howToApply: "1. Visit eshram.gov.in and click 'Register on e-SHRAM'\n2. Enter Aadhaar-linked mobile number\n3. Verify with OTP\n4. Fill occupation and bank details\n5. Download e-SHRAM card instantly\n6. Card can also be made at CSC",
    officialLink: "https://eshram.gov.in",
    deadline: null,
    termsAndConditions: ["Registration is completely free", "Must update profile periodically", "Accident insurance valid for 1 year, renewable", "Workers can link multiple occupations"],
    isState: false,
    state: null,
    tags: ["unorganised worker", "social security", "insurance", "registration"],
    popularityScore: 84,
  },
  {
    id: "pmsym-024",
    name: "PM Shram Yogi Maan-dhan",
    nameHindi: "प्रधानमंत्री श्रम योगी मान-धन",
    ministry: "Ministry of Labour and Employment",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["pension", "social-security"],
    incomeLimit: 1500000,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Guaranteed ₹3,000/month pension after age 60",
    description: "PM Shram Yogi Maan-dhan (PM-SYM) is a pension scheme for unorganised sector workers providing assured monthly pension of ₹3,000 after attaining the age of 60 years, on a minimum contribution of as low as ₹55/month.\n\nThe central government matches every contribution made by the subscriber. Workers in informal sector like street vendors, rickshaw pullers, construction workers, domestic workers benefit most from this scheme.",
    eligibility: ["Unorganised sector worker", "Age 18-40 years at enrollment", "Monthly income up to ₹15,000", "Not covered under NPS/EPFO/ESIC", "Active bank account and mobile number"],
    documents: ["Aadhaar Card", "Bank Savings Account passbook", "Mobile number"],
    howToApply: "1. Visit nearest CSC (Common Service Centre)\n2. Or enroll through maandhan.in portal\n3. Bring Aadhaar and bank passbook\n4. Contribution auto-deducted monthly from bank account\n5. Receive PM-SYM pension card",
    officialLink: "https://maandhan.in",
    deadline: null,
    termsAndConditions: ["Government matches every rupee contribution", "Monthly contribution ranges ₹55–₹200 depending on age", "On death, spouse gets 50% of pension", "Exit before 60: get back own contribution with interest", "Cannot receive other pension scheme benefits"],
    isState: false,
    state: null,
    tags: ["pension", "unorganised worker", "retirement", "social security"],
    popularityScore: 79,
  },
  {
    id: "nps-025",
    name: "National Pension System (NPS)",
    nameHindi: "राष्ट्रीय पेंशन प्रणाली",
    ministry: "Ministry of Finance / PFRDA",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["pension"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Market-linked pension savings + 60% lump sum tax-free at retirement",
    description: "National Pension System (NPS) is a voluntary, defined contribution retirement savings scheme to enable subscribers to make optimum decisions regarding their future through systematic savings during their working life.\n\nSubscribers can withdraw 60% of the corpus as lump sum (tax-free) on retirement, with 40% used to buy an annuity for monthly pension. Additional tax deduction of ₹50,000 under Section 80CCD(1B) over and above ₹1.5 lakh under 80C.",
    eligibility: ["Indian citizen", "Age 18-70 years", "Both salaried and self-employed eligible", "NRIs also eligible", "KYC compliant"],
    documents: ["Aadhaar Card", "PAN Card", "Bank account details", "Photograph", "Cancelled cheque"],
    howToApply: "1. Open NPS account at any Point of Presence (PoP) – banks, post offices\n2. Or apply online at enps.nsdl.com\n3. Get PRAN (Permanent Retirement Account Number)\n4. Make minimum contribution of ₹500 (Tier I)\n5. Choose investment fund manager and asset mix\n6. Monitor and contribute regularly",
    officialLink: "https://npscra.nsdl.co.in",
    deadline: null,
    termsAndConditions: ["Minimum contribution ₹1,000 per year in Tier I", "Partial withdrawal allowed for specified purposes after 3 years", "Full withdrawal allowed at 60 years", "60% tax-free lump sum at retirement", "40% must be used for annuity"],
    isState: false,
    state: null,
    tags: ["pension", "retirement", "investment", "tax savings"],
    popularityScore: 81,
  },
  {
    id: "ddu-gky-026",
    name: "Deen Dayal Upadhyaya Grameen Kaushalya Yojana",
    nameHindi: "दीन दयाल उपाध्याय ग्रामीण कौशल्य योजना",
    ministry: "Ministry of Rural Development",
    ageGroups: ["youngAdult", "teen"],
    sectors: ["skill-training", "employment"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Free residential skill training + placement in formal sector jobs",
    description: "DDU-GKY is a placement-linked, demand-driven rural skill training programme that targets rural youth between the age of 15-35 years. The programme trains rural youth in various skills and provides placement in private sector jobs with wages above minimum wage.\n\nThe scheme provides free residential training, accommodation, meals, uniform, and tools. Post-training, candidates are placed in jobs with a salary of at least ₹6,000/month. The programme focuses on SC/ST/minorities and women.",
    eligibility: ["Rural youth", "Age 15-35 years (up to 45 for specially abled and women)", "Family member of MGNREGS job card holder preferred", "SC/ST/minorities/women given priority", "No minimum education requirement for most trades"],
    documents: ["Aadhaar Card", "MGNREGS Job Card (if applicable)", "Caste Certificate", "Education certificate (if available)", "Bank passbook", "Photograph"],
    howToApply: "1. Contact your Gram Panchayat or Block Development Office\n2. Or visit nearest DDU-GKY Training Centre\n3. Or apply online at skillindiadigital.gov.in\n4. Attend awareness camp for scheme details\n5. Complete enrollment with documents\n6. Training starts in residential campus",
    officialLink: "https://skillindiadigital.gov.in",
    deadline: null,
    termsAndConditions: ["Training is completely free including accommodation and meals", "Must attend minimum 80% training sessions", "Placement guaranteed in formal sector", "Post-placement support for 1 year", "Must maintain job for minimum 3 months"],
    isState: false,
    state: null,
    tags: ["skill training", "rural", "placement", "employment", "youth"],
    popularityScore: 76,
  },

  // ──────────────── MIDDLE AGE SCHEMES ────────────────
  {
    id: "pm-kisan-009",
    name: "PM Kisan Samman Nidhi",
    nameHindi: "प्रधानमंत्री किसान सम्मान निधि",
    ministry: "Ministry of Agriculture",
    ageGroups: ["middleAge", "senior"],
    sectors: ["agriculture"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹6,000/year in 3 installments directly to bank",
    description: "PM-KISAN provides financial benefit of ₹6,000 per year to all farmer families in three equal installments of ₹2,000 each every four months. The fund is directly transferred via DBT mechanism.\n\nSmall and marginal farmers and all landholding farmers are covered. The scheme has disbursed over ₹2 lakh crore to farmers.",
    eligibility: ["Farmer family owning cultivable land", "Land records must be in name of farmer", "Indian citizen", "Active bank account for DBT"],
    documents: ["Aadhaar Card", "Land ownership documents", "Bank account passbook"],
    howToApply: "1. Register at pmkisan.gov.in\n2. Or visit the nearest CSC\n3. Enter land and Aadhaar details\n4. Submit land ownership documents\n5. Registration verified by state agriculture department\n6. Installments directly credited to bank account",
    officialLink: "https://pmkisan.gov.in",
    deadline: null,
    termsAndConditions: ["Farmer must have valid land records", "Self-declaration required about land ownership", "Excluded if family member is government employee earning above threshold", "Must update Aadhaar linkage in bank account"],
    isState: false,
    state: null,
    tags: ["farmer", "agriculture", "direct benefit", "income support"],
    popularityScore: 97,
  },
  {
    id: "atal-pension-010",
    name: "Atal Pension Yojana",
    nameHindi: "अटल पेंशन योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["pension", "social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Guaranteed pension ₹1,000–₹5,000/month after age 60",
    description: "Atal Pension Yojana (APY) is a pension scheme for unorganised sector workers providing guaranteed minimum pension of ₹1,000 to ₹5,000 per month at age 60. The government co-contributes 50% of total contribution or ₹1,000 per annum for non-income tax payers.\n\nContribution amount depends on subscriber's age at joining and desired pension amount.",
    eligibility: ["Indian citizen", "Age 18-40 years", "Active bank account with PFRDA-registered bank", "Not covered under statutory social security scheme", "Not an income tax payer for government co-contribution"],
    documents: ["Aadhaar Card", "Bank account details", "Mobile number"],
    howToApply: "1. Visit your bank branch where you have a savings account\n2. Fill the APY registration form\n3. Provide Aadhaar and bank account details\n4. Choose the desired pension amount (₹1000-₹5000)\n5. Set up auto-debit for contributions\n6. Receive a PRAN",
    officialLink: "https://npscra.nsdl.co.in/atal-pension-yojana.php",
    deadline: null,
    termsAndConditions: ["Early exit allowed only in exceptional circumstances", "On death before 60, nominee can continue or withdraw", "Government co-contribution for non-tax payers only", "Auto-debit mandatory"],
    isState: false,
    state: null,
    tags: ["pension", "retirement", "financial security"],
    popularityScore: 85,
  },
  {
    id: "pm-jan-dhan-011",
    name: "PM Jan Dhan Yojana",
    nameHindi: "प्रधानमंत्री जन धन योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["youngAdult", "middleAge", "senior"],
    sectors: ["social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Zero balance account + ₹2 lakh accident insurance + overdraft facility",
    description: "Pradhan Mantri Jan Dhan Yojana (PMJDY) ensures access to banking, savings, remittance, credit, insurance, and pension services for excluded sections. Zero balance account with RuPay debit card having ₹2 lakh accident insurance and ₹30,000 life insurance.\n\nOverdraft facility of up to ₹10,000 available to eligible account holders.",
    eligibility: ["Indian citizen", "Age 10 years and above", "Unbanked individuals prioritized", "No minimum balance required"],
    documents: ["Aadhaar Card", "Voter ID or Passport (alternative ID)", "Passport photograph"],
    howToApply: "1. Visit any bank branch, Bank Mitra (BC), or CSC\n2. Fill the account opening form\n3. Submit identity proof (Aadhaar preferred)\n4. Get RuPay debit card issued\n5. Account opened with zero balance",
    officialLink: "https://pmjdy.gov.in",
    deadline: null,
    termsAndConditions: ["Zero minimum balance unless overdraft used", "Overdraft facility only after 6 months of satisfactory operation", "Insurance cover linked to RuPay card", "Nominee required for insurance claim"],
    isState: false,
    state: null,
    tags: ["banking", "financial inclusion", "insurance", "DBT"],
    popularityScore: 93,
  },
  {
    id: "kisan-credit-card-027",
    name: "Kisan Credit Card (KCC)",
    nameHindi: "किसान क्रेडिट कार्ड",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    ageGroups: ["middleAge", "senior"],
    sectors: ["agriculture", "business-loans"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Short-term credit up to ₹3 lakh at 4% interest (subsidized)",
    description: "Kisan Credit Card (KCC) provides farmers with timely and adequate credit for their agricultural operations at concessional interest rates. Farmers can borrow up to ₹3 lakh at 4% per annum interest (after 3% interest subvention) for crop loans.\n\nThe card also provides credit for post-harvest expenses, maintenance of farm assets, and consumption requirements. KCC acts like a revolving credit facility with a 5-year validity.",
    eligibility: ["Farmer, sharecropper, or tenant farmer", "Allied activities like animal husbandry and fisheries also eligible", "Indian citizen", "No default on agricultural loans", "Viable agricultural land or activity"],
    documents: ["Aadhaar Card", "Land ownership/tenancy documents", "Bank account details", "Passport photograph", "PAN Card (for loans above ₹1 lakh)"],
    howToApply: "1. Visit your nearest bank branch (all commercial banks and cooperative banks)\n2. Fill the KCC application form\n3. Submit land documents and KYC papers\n4. Bank assesses creditworthiness and land holding\n5. KCC issued within 2 weeks of application\n6. ATM card for cash withdrawal also provided",
    officialLink: "https://www.nabard.org/content1.aspx?id=572&catid=23&mid=530",
    deadline: null,
    termsAndConditions: ["Credit limit based on land holding and crop pattern", "Repayment within 12 months of each disbursement", "Annual review of credit limit", "Crop insurance mandatory", "Interest subvention only if repaid on time"],
    isState: false,
    state: null,
    tags: ["farmer", "credit", "agriculture", "loan"],
    popularityScore: 89,
  },
  {
    id: "msme-eclgs-028",
    name: "Emergency Credit Line Guarantee Scheme (ECLGS)",
    nameHindi: "आपातकालीन क्रेडिट लाइन गारंटी योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["middleAge", "youngAdult"],
    sectors: ["business-loans", "startup-business"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "100% government guarantee on additional loans up to 20% of outstanding credit",
    description: "The Emergency Credit Line Guarantee Scheme (ECLGS) provides additional credit of up to 20% of outstanding credit to MSMEs and business enterprises at a capped interest rate of 9.25% for banks and 14% for NBFCs.\n\nThe scheme provides 100% credit guarantee, meaning MSMEs don't need additional collateral. Repayment period is 4 years including a 12-month moratorium on principal repayment.",
    eligibility: ["MSME or business enterprise", "Outstanding credit up to ₹50 crore (for ECLGS 1.0)", "No NPA (Non-Performing Asset) as of February 2020", "GST registered preferred", "Indian entity"],
    documents: ["GST registration", "Business financial statements", "Existing loan documents", "Aadhaar and PAN of proprietor/directors", "Bank account details"],
    howToApply: "1. Contact your existing bank/NBFC where you have business loan\n2. They will check your eligibility automatically\n3. Fill the ECLGS application form\n4. Bank processes and disburses additional credit\n5. No additional collateral required",
    officialLink: "https://www.ncgtc.in",
    deadline: null,
    termsAndConditions: ["Moratorium on principal for 12 months", "No prepayment penalty", "Available only through existing lenders", "GST returns to be submitted regularly", "Business must be operational"],
    isState: false,
    state: null,
    tags: ["MSME", "business", "credit", "emergency", "loan"],
    popularityScore: 75,
  },
  {
    id: "pm-awas-rural-029",
    name: "PM Awas Yojana (Gramin)",
    nameHindi: "प्रधानमंत्री आवास योजना (ग्रामीण)",
    ministry: "Ministry of Rural Development",
    ageGroups: ["middleAge", "youngAdult", "senior"],
    sectors: ["housing"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹1.2–1.3 lakh grant for constructing a pucca house (plain areas); ₹1.3 lakh (hilly/NE states)",
    description: "Pradhan Mantri Awaas Yojana – Gramin (PMAY-G) aims to achieve 'Housing for All' in rural areas by providing assistance to BPL families for construction of safe and durable houses. Each beneficiary gets a grant of ₹1.20 lakh (plain areas) or ₹1.30 lakh (hilly/NE/IAP districts).\n\nBeneficiaries also get 90 person-days of unskilled labour under MGNREGS. All payments are made directly to bank accounts. Construction is monitored through geo-tagged photographs.",
    eligibility: ["Houseless or living in kutcha/dilapidated house", "Listed in SECC 2011 permanent wait list or Awaas+ survey", "SC/ST/OBC/minorities get priority", "Must have a functional toilet (can be built under Swachh Bharat)", "Rural resident"],
    documents: ["Aadhaar Card", "SECC/Awaas+ listing proof", "Bank account passbook", "Photograph of existing dwelling", "Caste certificate (if applicable)"],
    howToApply: "1. Eligibility automatically determined from SECC 2011 data\n2. Beneficiaries informed through Gram Sabha\n3. Register at pmayg.nic.in or through Gram Panchayat\n4. Complete the application with Gram Panchayat assistance\n5. Funds released in installments based on construction progress\n6. Progress monitored through AwaasSoft mobile app",
    officialLink: "https://pmayg.nic.in",
    deadline: null,
    termsAndConditions: ["House must be completed within 12 months of first installment", "Must include toilet as per Swachh Bharat Abhiyan", "Beneficiary must construct themselves or with hired labour", "Cannot sell or transfer property for 10 years", "Progress monitored through geo-tagged photos"],
    isState: false,
    state: null,
    tags: ["housing", "rural", "pucca house", "BPL", "construction"],
    popularityScore: 91,
  },
  {
    id: "pm-suraksha-bima-030",
    name: "PM Suraksha Bima Yojana",
    nameHindi: "प्रधानमंत्री सुरक्षा बीमा योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["social-security", "health-insurance"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹2 lakh accidental death & disability insurance at only ₹20/year",
    description: "PM Suraksha Bima Yojana (PMSBY) provides accidental death and disability insurance at an annual premium of just ₹20. The scheme offers ₹2 lakh cover for accidental death or total permanent disability, and ₹1 lakh for partial permanent disability.\n\nThe premium is auto-debited from the bank account on or before 1st June each year. It is one of the most affordable insurance schemes in the world.",
    eligibility: ["Indian citizen", "Age 18-70 years", "Savings bank account", "Aadhaar linked to bank account preferred", "Auto-debit consent given"],
    documents: ["Aadhaar Card", "Savings bank account details", "Mobile number"],
    howToApply: "1. Visit your bank branch or net banking portal\n2. Fill the PMSBY application form\n3. Give auto-debit consent for ₹20 annual premium\n4. Enrollment valid from 1 June to 31 May\n5. Coverage starts immediately on enrollment\n6. Claim through bank in case of accident",
    officialLink: "https://jansuraksha.gov.in",
    deadline: null,
    termsAndConditions: ["Annual renewal required", "Coverage excludes self-inflicted injuries", "Claim must be made within 30 days of accident", "Both accidental death and disability covered", "Maximum 2 accounts per individual"],
    isState: false,
    state: null,
    tags: ["insurance", "accident", "cheap insurance", "social security"],
    popularityScore: 88,
  },
  {
    id: "pm-jeevan-jyoti-031",
    name: "PM Jeevan Jyoti Bima Yojana",
    nameHindi: "प्रधानमंत्री जीवन ज्योति बीमा योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹2 lakh life insurance at only ₹436/year",
    description: "PM Jeevan Jyoti Bima Yojana (PMJJBY) offers renewable term life insurance covering death from any cause at an annual premium of ₹436. The scheme provides ₹2 lakh to the nominee in case of the policy holder's death.\n\nThe premium is auto-debited from the bank account. This is one of the cheapest term insurance schemes offered by the government.",
    eligibility: ["Indian citizen", "Age 18-50 years", "Savings bank account", "Consent for auto-debit", "Can join up to age 55 if enrolled before 50"],
    documents: ["Aadhaar Card", "Bank savings account details", "Nominee details", "Mobile number"],
    howToApply: "1. Visit bank branch or net banking\n2. Fill PMJJBY enrollment form\n3. Nominate a family member\n4. Give auto-debit consent for ₹436/year\n5. Coverage valid for 1 year (June to May)\n6. Claim processed through bank by nominee",
    officialLink: "https://jansuraksha.gov.in",
    deadline: null,
    termsAndConditions: ["Annual renewal mandatory", "Coverage for death from any cause", "Suicide in first year not covered", "Claim by nominee within 30 days of death", "Cannot have more than one PMJJBY policy"],
    isState: false,
    state: null,
    tags: ["life insurance", "term insurance", "death benefit", "social security"],
    popularityScore: 86,
  },
  {
    id: "pm-garib-kalyan-032",
    name: "PM Garib Kalyan Anna Yojana",
    nameHindi: "प्रधानमंत्री गरीब कल्याण अन्न योजना",
    ministry: "Ministry of Food and Consumer Affairs",
    ageGroups: ["middleAge", "senior", "youngAdult"],
    sectors: ["social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "5 kg free food grains per person per month",
    description: "PM Garib Kalyan Anna Yojana (PMGKAY) provides 5 kg of free food grains (rice/wheat/coarse grains) per person per month to beneficiaries under the National Food Security Act (NFSA).\n\nThe scheme covers about 81.35 crore beneficiaries under NFSA. Food grains are distributed through the Public Distribution System (PDS) via Fair Price Shops.",
    eligibility: ["Listed under National Food Security Act (NFSA)", "Antodaya Anna Yojana (AAY) card holder", "Priority Household (PHH) card holder", "Any category (no income restriction for NFSA listed)"],
    documents: ["Ration Card", "Aadhaar Card", "Registration in NFSA system"],
    howToApply: "1. If not already listed in NFSA, apply at State Food Department\n2. Existing NFSA beneficiaries automatically covered\n3. Collect food grains from designated Fair Price Shop (ration shop)\n4. Show Aadhaar for biometric verification at PDS shop\n5. No separate application needed for existing beneficiaries",
    officialLink: "https://dfpd.gov.in/pmgkay.htm",
    deadline: null,
    termsAndConditions: ["Available at designated Fair Price Shops only", "Monthly allocation per eligible family", "Ration card and Aadhaar required for collection", "Cannot collect on behalf of others without authorization"],
    isState: false,
    state: null,
    tags: ["food security", "ration", "free food", "PDS"],
    popularityScore: 96,
  },
  {
    id: "pm-fasal-bima-015",
    name: "PM Fasal Bima Yojana",
    nameHindi: "प्रधानमंत्री फसल बीमा योजना",
    ministry: "Ministry of Agriculture",
    ageGroups: ["middleAge", "senior"],
    sectors: ["agriculture"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Crop insurance with minimum 2% premium for Kharif, 1.5% for Rabi",
    description: "Pradhan Mantri Fasal Bima Yojana (PMFBY) provides comprehensive crop insurance against crop loss due to unforeseen events. Farmers pay 2% for Kharif crops, 1.5% for Rabi crops, and 5% for commercial crops. The remaining premium is shared by central and state governments.\n\nCoverage from pre-sowing to post-harvest including hailstorm, landslide, and flood.",
    eligibility: ["Farmer growing notified crops in notified areas", "Both loanee and non-loanee farmers eligible", "Sharecroppers and tenant farmers also eligible", "Must have land records or valid tenancy agreement"],
    documents: ["Land records/tenancy documents", "Aadhaar Card", "Bank account passbook", "Sowing certificate"],
    howToApply: "1. Apply through your bank during crop season\n2. Or visit nearest CSC/insurance company office\n3. Or apply online at pmfby.gov.in\n4. Submit land and crop details\n5. Pay the applicable premium\n6. Claim process initiated automatically on notified calamities",
    officialLink: "https://pmfby.gov.in",
    deadline: null,
    termsAndConditions: ["Mandatory for farmers taking Kisan Credit Card loans", "Enrollment must be done before cutoff date each season", "Claims settled through Remote Sensing and Crop Cutting Experiments", "Area approach for coverage"],
    isState: false,
    state: null,
    tags: ["farmer", "agriculture", "insurance", "crop"],
    popularityScore: 86,
  },
  {
    id: "stand-up-india-016",
    name: "Stand-Up India",
    nameHindi: "स्टैंड अप इंडिया",
    ministry: "Ministry of Finance",
    ageGroups: ["youngAdult", "middleAge"],
    sectors: ["startup-business", "business-loans"],
    incomeLimit: null,
    categories: ["sc", "st", "women"],
    benefit: "Loans ₹10 lakh to ₹1 crore for SC/ST/Women entrepreneurs",
    description: "Stand-Up India facilitates bank loans between ₹10 lakh and ₹1 crore to SC/ST and women borrowers for setting up greenfield enterprises in manufacturing, services, or trading.\n\nProvides handholding support through credit guarantee, refinancing via SIDBI, and a web portal for credit facilitation.",
    eligibility: ["SC/ST or woman entrepreneur", "Age 18 years and above", "Setting up a greenfield enterprise", "Not in default to any bank/financial institution", "Business in manufacturing, services or trading"],
    documents: ["Aadhaar Card", "PAN Card", "Caste certificate (for SC/ST)", "Business plan", "Bank statements", "Proof of non-default"],
    howToApply: "1. Apply at nearest bank branch\n2. Or apply online through standupmitra.in portal\n3. Submit business plan and KYC documents\n4. Bank evaluates business viability\n5. Get handholding support if needed\n6. Loan disbursed on approval",
    officialLink: "https://www.standupmitra.in",
    deadline: null,
    termsAndConditions: ["Loan tenure up to 7 years", "For greenfield enterprises only", "Collateral as per bank norms or NCGTC cover", "Composite loan (term loan + working capital)"],
    isState: false,
    state: null,
    tags: ["loan", "SC/ST", "women", "entrepreneur", "startup"],
    popularityScore: 79,
  },
  {
    id: "pm-svanidhi-017",
    name: "PM SVANidhi Scheme",
    nameHindi: "पीएम स्वनिधि योजना",
    ministry: "Ministry of Housing and Urban Affairs",
    ageGroups: ["middleAge", "senior", "youngAdult"],
    sectors: ["startup-business", "business-loans"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Working capital loan ₹10,000–₹50,000 for street vendors",
    description: "PM SVANidhi provides affordable working capital loans to street vendors, with first loan of ₹10,000 enhanced to ₹20,000 and ₹50,000 on timely repayment. Digital transactions incentivized through cashback up to ₹1,200 per annum.\n\nHelps vendors graduate from debt traps of moneylenders to formal banking system.",
    eligibility: ["Street vendor in urban areas", "Vending on or before 24 March 2020", "Certificate of Vending or Letter of Recommendation from ULB", "Indian citizen"],
    documents: ["Aadhaar Card", "Certificate of Vending / Letter of Recommendation", "Bank account details", "Photographs"],
    howToApply: "1. Apply through pmsvanidhi.mohua.gov.in or mobile app\n2. Or apply at MFI/NBFC/Bank\n3. Get Certificate of Vending from Urban Local Body (ULB)\n4. Submit application with documents\n5. Loan disbursed quickly (usually within 30 days)",
    officialLink: "https://pmsvanidhi.mohua.gov.in",
    deadline: null,
    termsAndConditions: ["Loan tenure: 1 year for ₹10,000, 18 months for ₹20,000, 36 months for ₹50,000", "Interest subvention of 7% per annum", "Digital transaction cashback up to ₹1,200 per year", "Timely repayment required for enhanced loans"],
    isState: false,
    state: null,
    tags: ["street vendor", "loan", "working capital", "urban"],
    popularityScore: 81,
  },

  // ──────────────── SENIOR CITIZEN SCHEMES ────────────────
  {
    id: "ignoapss-012",
    name: "Indira Gandhi National Old Age Pension Scheme",
    nameHindi: "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना",
    ministry: "Ministry of Rural Development",
    ageGroups: ["senior"],
    sectors: ["pension", "old-age-support"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹300-₹500/month pension (central component)",
    description: "Indira Gandhi National Old Age Pension Scheme (IGNOAPS) provides income support to the elderly poor. Central government provides ₹300/month for persons aged 60-79 years and ₹500/month for those aged 80+ who are BPL.\n\nState governments can add contributions on top, making the effective pension higher in many states.",
    eligibility: ["Indian citizen", "Age 60 years and above", "Below Poverty Line (BPL) category", "Has no or minimal means of subsistence from own source"],
    documents: ["Aadhaar Card", "Age proof (birth certificate, school certificate)", "BPL certificate/Ration Card", "Bank passbook", "Passport photograph"],
    howToApply: "1. Apply at the Gram Panchayat office (rural) or Ward office (urban)\n2. Fill the pension application form\n3. Submit age proof and BPL documents\n4. Verification done by local authorities\n5. Pension approved by District Collector/SDM\n6. Amount credited directly to bank account",
    officialLink: "https://nsap.nic.in",
    deadline: null,
    termsAndConditions: ["Must be BPL cardholder", "Pension stops on death of beneficiary", "Annual verification of eligibility required", "Cannot get multiple pensions simultaneously"],
    isState: false,
    state: null,
    tags: ["pension", "old age", "poverty", "social security"],
    popularityScore: 87,
  },
  {
    id: "pmvvy-013",
    name: "Pradhan Mantri Vaya Vandana Yojana",
    nameHindi: "प्रधानमंत्री वय वंदना योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["senior"],
    sectors: ["pension", "social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Guaranteed 7.4% return, up to ₹9,250/month pension",
    description: "Pradhan Mantri Vaya Vandana Yojana (PMVVY) offers guaranteed return of 7.4% per annum for 10 years to senior citizens aged 60+. Maximum investment of ₹15 lakh per senior citizen gives maximum monthly pension of ₹9,250.\n\nImplemented through LIC of India. On death during policy term, purchase price is returned to beneficiary.",
    eligibility: ["Indian citizen", "Age 60 years and above", "Investment of ₹1.5 lakh to ₹15 lakh", "Purchased through LIC of India"],
    documents: ["Aadhaar Card", "Age proof", "Bank account details", "Cancelled cheque", "Photographs"],
    howToApply: "1. Visit nearest LIC branch or apply online at licindia.in\n2. Fill the PMVVY application form\n3. Submit KYC documents\n4. Pay the lump sum premium (investment amount)\n5. Receive policy documents\n6. Pension credited monthly to bank account",
    officialLink: "https://licindia.in/PMVVY",
    deadline: "31 March 2023 (scheme closed for new subscribers)",
    termsAndConditions: ["Loan facility available after 3 years (up to 75% of purchase price)", "Premature exit allowed on critical illness", "On premature exit, 98% of purchase price refunded"],
    isState: false,
    state: null,
    tags: ["pension", "investment", "senior", "LIC"],
    popularityScore: 80,
  },
  {
    id: "scss-014",
    name: "Senior Citizens Savings Scheme",
    nameHindi: "वरिष्ठ नागरिक बचत योजना",
    ministry: "Ministry of Finance",
    ageGroups: ["senior"],
    sectors: ["social-security", "pension"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "8.2% interest per annum (highest among government schemes)",
    description: "Senior Citizens Savings Scheme (SCSS) offers 8.2% per annum interest with quarterly payouts. Maximum deposit of ₹30 lakh with 5-year tenure extendable by 3 years. Tax benefits under Section 80C.\n\nAvailable at authorized post offices and banks across India.",
    eligibility: ["Indian citizen", "Age 60 years and above", "Retired civilian employees of age 55-60 also eligible", "Defence personnel from age 50 eligible"],
    documents: ["Age proof", "Address proof", "PAN card", "Passport photographs"],
    howToApply: "1. Visit nearest post office or authorized bank\n2. Fill SCSS account opening form\n3. Submit KYC documents\n4. Deposit amount (minimum ₹1,000, maximum ₹30 lakh)\n5. Interest credited quarterly to linked savings account",
    officialLink: "https://www.indiapost.gov.in/Financial/pages/content/scss.aspx",
    deadline: null,
    termsAndConditions: ["Maximum deposit ₹30 lakh per account", "Joint account possible only with spouse", "Premature withdrawal allowed with penalty", "TDS deducted if annual interest exceeds ₹50,000"],
    isState: false,
    state: null,
    tags: ["savings", "interest", "senior", "investment"],
    popularityScore: 83,
  },
  {
    id: "rashtriya-vayoshri-033",
    name: "Rashtriya Vayoshri Yojana",
    nameHindi: "राष्ट्रीय वयोश्री योजना",
    ministry: "Ministry of Social Justice and Empowerment",
    ageGroups: ["senior"],
    sectors: ["old-age-support", "health-insurance"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "Free assistive living devices (walking sticks, wheelchairs, hearing aids, spectacles)",
    description: "Rashtriya Vayoshri Yojana (RVY) provides physical aids and assistive living devices to senior citizens belonging to BPL category who suffer from age-related disabilities/infirmities. The scheme ensures that poor senior citizens live with dignity and independence.\n\nAssistive devices include walking sticks, elbow crutches, walkers/crutches, tripods/quadpods, hearing aids, wheelchairs, artificial dentures, and spectacles. All devices conform to BIS standards.",
    eligibility: ["Senior citizen aged 60 years and above", "Below Poverty Line (BPL) category", "Must suffer from age-related disabilities", "Indian citizen", "Residing in India"],
    documents: ["Aadhaar Card", "Age proof", "BPL Ration Card", "Medical certificate of disability/infirmity", "Photograph"],
    howToApply: "1. Contact the District Social Welfare Officer or nearby CSC\n2. Or apply through Artificial Limbs Manufacturing Corporation (ALIMCO)\n3. Medical screening camps held in districts\n4. Devices distributed free at camp sites\n5. Apply also at socialjustice.gov.in",
    officialLink: "https://socialjustice.gov.in/schemes/73",
    deadline: null,
    termsAndConditions: ["One-time provision of devices per beneficiary", "Devices replaced only after prescribed life period", "Must be BPL to qualify", "Medical screening mandatory for device selection"],
    isState: false,
    state: null,
    tags: ["senior", "disability", "assistive devices", "BPL"],
    popularityScore: 71,
  },
  {
    id: "igndps-034",
    name: "Indira Gandhi National Disability Pension Scheme",
    nameHindi: "इंदिरा गांधी राष्ट्रीय विकलांगता पेंशन योजना",
    ministry: "Ministry of Rural Development",
    ageGroups: ["middleAge", "senior"],
    sectors: ["old-age-support", "social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "₹300/month central pension (state may add more)",
    description: "Indira Gandhi National Disability Pension Scheme (IGNDPS) provides monthly pension to severely disabled persons from BPL households. The central government provides ₹300/month, and states supplement with additional amounts.\n\nThe scheme covers persons with severe or multiple disabilities (80% or more disability) aged 18 years and above.",
    eligibility: ["Person with severe or multiple disabilities (80%+ disability)", "Age 18 years and above", "BPL household", "Indian citizen", "Disability certified by government medical board"],
    documents: ["Aadhaar Card", "Disability Certificate (80%+) from govt hospital", "BPL Certificate/Ration Card", "Age proof", "Bank passbook", "Photograph"],
    howToApply: "1. Apply at Gram Panchayat (rural) or Ward Office (urban)\n2. Submit disability certificate from government medical board\n3. Verification by local authorities\n4. Approved by District Collector\n5. Pension credited directly to bank account",
    officialLink: "https://nsap.nic.in",
    deadline: null,
    termsAndConditions: ["Disability must be 80% or more as certified", "Annual verification required", "Cannot receive alongside old age pension", "Pension stops if disability reduces below 80%"],
    isState: false,
    state: null,
    tags: ["disability", "pension", "BPL", "social security"],
    popularityScore: 68,
  },
  {
    id: "annapurna-035",
    name: "Annapurna Scheme",
    nameHindi: "अन्नपूर्णा योजना",
    ministry: "Ministry of Rural Development",
    ageGroups: ["senior"],
    sectors: ["old-age-support", "social-security"],
    incomeLimit: null,
    categories: ["general", "obc", "sc", "st"],
    benefit: "10 kg free food grain per month to destitute seniors",
    description: "The Annapurna Scheme provides 10 kg of food grains per month free of cost to destitute senior citizens who are not getting pension under any state or central pension scheme despite being eligible. It targets those who have 'slipped through the net' of other schemes.\n\nThe scheme covers those who are aged 65 years and above, eligible for old age pension but not getting it.",
    eligibility: ["Senior citizen aged 65 years and above", "Destitute (no regular income or financial support)", "Not already getting old age pension", "Not covered under NFSA/TPDS", "BPL household"],
    documents: ["Aadhaar Card", "Age proof", "BPL certificate", "Self-declaration of no pension", "Photograph"],
    howToApply: "1. Apply at Gram Panchayat (rural) or Ward Office (urban)\n2. Submit age proof and BPL documents\n3. Self-declare that no pension is being received\n4. Approved by District Collector\n5. Food grains collected from designated Fair Price Shop",
    officialLink: "https://nsap.nic.in",
    deadline: null,
    termsAndConditions: ["Only for those not getting any pension", "Grains collected monthly from PDS shop", "Annual verification of eligibility", "10 kg per beneficiary per month (not per family)"],
    isState: false,
    state: null,
    tags: ["food", "senior", "destitute", "free grains"],
    popularityScore: 65,
  },
];

export async function seedDatabase() {
  // Always try to insert all schemes with onConflictDoNothing – safe to run on every start
  for (const scheme of schemes) {
    await db.insert(schemesTable).values(scheme).onConflictDoNothing();
  }

  const existingSectors = await db.select({ sectorId: sectorsTable.sectorId }).from(sectorsTable);
  if (existingSectors.length === 0) {
    for (const sector of sectors) {
      await db.insert(sectorsTable).values(sector).onConflictDoNothing();
    }
    console.log(`Seeded ${sectors.length} sectors`);
  }
  console.log(`Seeded/verified ${schemes.length} schemes`);
}
